### ISSUE TITLE
No UTF-8 keyboard input in psysh

### ISSUE THREAD

**Issue by tkn98** [bobthecow/psysh#148] opened 2015-02-10 13:37 UTC
When I run psysh and type in oumlaut ("`ö`") for example as part of the word "`Göttin`" (german for goddess) the letter won't be accepted. Instead "`Gttin`" will be written.

When I type "`größe`" (with szlig) "`grgre`" will be written. Similar with middle mouse button.

In the terminal itself, this is no problem at all. Only then the shell is started. My version:

> Psy Shell v0.3.3 (PHP 5.5.9-1ubuntu4.5 — cli) by Justin Hileman

**Comment by bobthecow** [comment] 2015-02-10 15:19
That's strange. PsySH should work great with UTF-8. I can't reproduce it on OS X, but I'll give it a shot in Ubuntu. Does it work with `php -a`?

**Comment by tkn98** [comment] 2015-02-10 15:25
Good to know this works on your platform. I also suspected this might be a platform issue.

Your nose is good, too. `php -a` has the exact same problems.

Perhaps this is a wrong compiled binary library on Ubuntu's PHP package?

This puzzle piece pops to mind: [Makefile bash autocompletion issue with PHP generated targets](http://stackoverflow.com/questions/16233321/makefile-bash-autocompletion-issue-with-php-generated-targets) - It's php cli related on ubuntu.

**Comment by bobthecow** [comment] 2015-02-10 15:32
What is the output of `readline_info`?

**Comment by tkn98** [comment] 2015-02-10 16:45
>>> readline_info();
	=> [
		   "line_buffer"               => "readline_info();\n",
		   "point"                     => 0,
		   "end"                       => 0,
		   "library_version"           => "EditLine wrapper",
		   "readline_name"             => "",
		   "attempted_completion_over" => 0
	   ]

**Comment by bobthecow** [comment] 2015-02-10 17:48
Okay, so it's compiled with libedit. Your shell is likely using readline. Maybe Ubuntu has crap libedit bindings/defaults?

**Comment by tkn98** [comment] 2015-02-10 18:54
as far as I learned libedit has been written for BSD systems and has problems with linux architecture. One example for such kind of problems is [libedit: patch to fix unexpected behavior on Linux (Jan 2011)](http://mail-index.netbsd.org/tech-userlevel/2011/01/26/msg004486.html).

One suggestion is to [re-compile PHP w/o `--with-libedit`](https://bugs.launchpad.net/ubuntu/+source/php5/+bug/322214/comments/2).

**Comment by bobthecow** [comment] 2015-02-10 19:18
> One suggestion is to re-compile PHP w/o `--with-libedit`.

If you do that, make sure to compile `--with-readline`. It's pretty awful with neither :)

**Comment by tkn98** [comment] 2015-02-10 19:55
Yes, I replaced the `--width-libedit=`... with `--with-readline`. Gilles [provided some guideline](http://unix.stackexchange.com/a/10978/9340) just [`libreadline-dev`](http://askubuntu.com/a/89394/55951) was missing for me. However tests didn't ran through so it stopped again with error. This might take some time until I will successfully manage to create that package.

**Comment by bobthecow** [comment] 2015-02-10 20:02
I've found the easiest thing to do is throw the linux box away and get a Mac ;)

**Comment by tkn98** [comment] 2015-02-11 08:22
Well, it's not that I would personally farvor that, however, this is a corporate desktop an I'm bound to the policy so I need to stick with kubuntu on this one. In any case it was my first PHP binary packaging from sources on that system so it's not that astonishing it didn't went flawlessly through taken I'm really new to this.

**Comment by Markcial** [comment] 2015-02-17 15:22
Might be related to this, https://bugs.launchpad.net/ubuntu/+source/libedit/+bug/816758, it happens to me too in my docker images based on debian or ubuntu, but not on my Mac

**Comment by tkn98** [comment] 2015-02-18 08:08
@Markcial: Thanks for sharing, that looks related indeed.

**Comment by bobthecow** [comment] 2015-02-19 05:30
If you disable readline in your psysh config, does it work with UTF-8 characters?

**Comment by tkn98** [comment] 2015-02-19 07:04
@bobthecow: Disabling readline

>    'useReadline' => false,

make it work with UTF-8 characters both for typing as well as for pasting.

**Comment by bobthecow** [comment] 2015-02-19 07:09
Unfortunately it also breaks other awesome things (like the upcoming tab completion) so that's not really a viable solution. It does seem to indicate that the issue is with libedit as suspected.

**Comment by bobthecow** [comment] 2015-02-23 18:45
You shouldn't need to recompile, you can just install the `php5-readline` package, right?

http://packages.ubuntu.com/trusty/php5-readline

**Comment by tkn98** [comment] 2015-02-24 09:59
@bobthecow: Yes, that php-readline is compile with libedit. That's why I thought it might be easier to recompile just that module but just with the readline C lib.

**Comment by jrobeson** [comment] 2015-07-13 09:57
definitely not a problem on Fedora (and thus likely not to be a problem on RHEL/CentOS)

**Comment by tkn98** [comment] 2015-07-13 12:01
@jrobeson: Do you know which readline library is used on Fedora for php5-readline (or php)? And on Fedora Remi does the packages, they normally just work top-notch and are up-to-the-date.

I dunno why I can't manage to find a solution on my office box here, I'm a bit disappointed I have to admit. Tried once to recompile the php-5 readline module but tests didn't went through two times and it was all over my head.

**Comment by ikari7789** [comment] 2015-07-28 05:13
I'm having the same problem on CentOS 6.6 in a VM. Any Japanese that I type is just gobbled up by the system and sent into the netherworld. Disabling readline does fix it, but makes it a real crapshoot to use. I'm also using Remi's PHP5.6 packages. php-readline is included as a part of the php-cli package. I haven't tried yet with a custom complied PHP (which we use for our production servers).

**Comment by tkn98** [comment] 2015-07-28 08:52
Most likely CentOS 6.6 doesn't have libedit fixed as well.

**Comment by ikari7789** [comment] 2015-07-29 01:32
Fixed it by hackishly installing the latest version on top of the system version. Since it's a VM I don't care much, but it seems to fix the problem. For anyone else that is experience the same problem and doesn't mind a hacky solution, they can try this. I rebooted afterwards and it worked.

    wget http://thrysoee.dk/editline/libedit-20150325-3.1.tar.gz
    tar xzvf http://thrysoee.dk/editline/libedit-20150325-3.1.tar.gz
    cp libedit-20150325-3.1
    ./configure --prefix=/usr --enable-widec
    make
    sudo make install

**Comment by tkn98** [comment] 2015-07-29 07:25
@ikari7789: thanks for sharing. Apart from some typos in that sequence I could also recompile on my Ubuntu system however I'm such a noob with this as it does not work (tm). It's perhaps just either not working (/usr/lib has new files and/or I need to reload something but prevent a reboot as I think this should *not* be necessary. In any case, thanks so far for the configure lines.

**Comment by ikari7789** [comment] 2015-07-29 08:20
@tkn98 I would advise to not do such a destructive operation in any kind of a stable environment as there could be unexpected side-affects. Though you should be able to recover from it if you just reinstall the system libedit package and remove any additional files that are generated by the new version that don't exist in the original version. The reboot may not be necessary, but since I'm working in a disposable VM, I can handle the 30 second reboot window. No idea what libedit is hooked into that needs restarted.

**Comment by tkn98** [comment] 2015-07-29 11:37
@ikari7789: So one library can only loaded once on a running system then I guess. The system here is under configuration management as well, so this shouldn't be an issue. Also it's a developer box. But thanks for the reminder :) I'll try a reboot and see if the system still comes up.

**Comment by bobthecow** [comment] 2015-11-26 00:00
@tkn98 (or anyone else with a system that exhibits this issue) if you run psysh inside `rlwrap` does it fix UTF-8 input?

**Comment by icedfish** [comment] 2015-11-26 02:00
@bobthecow I tried to use psysh inside rlwrap (version: PHP 5.5.9-1ubuntu4.14 ), it seems still not  working.

**Comment by tkn98** [comment] 2015-11-26 10:37
@bobthecow  I just tested rlwrap with php -a on that system. It does not make any difference regarding character encoding. So no, this didn't help, but thanks for the tip, I was not aware of rlwrap yet! :+1:

**Comment by bobthecow** [comment] 2015-11-26 14:55
rlwrap isn't as nice as real readline support compiled into PHP, because PsySH doesn't have access to it. So we can't do fancy tab completion or anything. But it is better than no readline at all :)

**Comment by mitghi** [comment] 2016-07-03 12:44
It's late, but I encountered this problem and created a package for it. You can find it here: https://github.com/mitghi/php5

**Comment by h311ion** [comment] 2016-11-11 11:42
Just if someone bumps into same problem - on ubuntu 15.10 with installed php5-readline - i just reinstalled (apt remove/install php5-readline) and problem gone.

**Comment by yangliuyu** [comment] 2017-06-08 00:33
I use psysh via php artisan tinker (part of laravel) in a customized docker instance (official php 7.1.5-alpine) which can not input utf8 characters like Chinese. 

The php in docker is compiled with --with-libedit and libedit version used is libedit-20150325.3.1-r3. It is not likely change php with --with-readline since it will build the php image from scratch. When I try to download the latest libedit and compile it, it pass the configure but failed at make as 
```
make[3]: Entering directory '/var/www/tmp/libedit-20170329-3.1/src'
make[3]: Warning: File 'Makefile' has modification time 2016 s in the future
  CC       chared.lo
In file included from el.h:50:0,
                 from chared.c:51:
chartype.h:41:3: error: #error wchar_t must store ISO 10646 characters
  #error wchar_t must store ISO 10646 characters
```
Some patch may [fix](http://lists.busybox.net/pipermail/buildroot/2016-January/149100.html) this problem but may need some extra effort.

The php installed on my mac via homebrew is compiled with readline works well.
```
--with-readline=/usr/local/opt/readline
``` 

The workaround for me is to add a config.php under ~/.config/psysh with the content as @tkn98 already mentioned. But the tab completion and history function not work.
```
<?php

return [
    'useReadline' => false,
];
```

**Comment by bobthecow** [comment] 2018-10-12 13:53
Closing this, as there's not a whole lot we can do from the PsySH end.

Note that if you install `hoa/console` (or use the `-compat` pre-built Phars, which include it) you can get back some of the features you lose by disabling readline. It implements readline in userland  PHP, so it's not perfect, but it's better than nothing :)

**Closed by bobthecow** 2018-10-12 13:53 UTC
Labels: docs
