### ISSUE TITLE
echo 0;

### ISSUE THREAD

**Issue by vstepanyuk** [bobthecow/psysh#289] opened 2016-02-25 15:15 UTC
```
>>> echo 0
=> null
```

```
>>> echo 1
1⏎
=> null
```

**Comment by vstepanyuk** [comment] 2016-02-25 15:15
```
>>> echo 1
1⏎
=> null
```

**Comment by bobthecow** [comment] 2016-02-25 19:36
Hmm. Interesting. I'll take a look.

**Comment by GrahamCampbell** [comment] 2016-02-25 19:38
This is NOT a bug in psysh. This is just how php's echo function works. 0 is cast to empty string, and 1 is cast to the string "1"/

**Comment by vstepanyuk** [comment] 2016-02-25 19:39
```
~ ❯❯❯ php -a
Interactive shell

php > echo 0;
0
php >
```

**Comment by GrahamCampbell** [comment] 2016-02-25 19:40
Hmmm. You're right. Very strange.

**Comment by bobthecow** [comment] 2016-02-25 19:45
Not all that strange. PHP's stupid `empty` implementation strikes again.

https://github.com/bobthecow/psysh/blob/master/src/Psy/Shell.php#L605

**Comment by vstepanyuk** [comment] 2016-02-25 19:47
http://php.net/empty

"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)

**Comment by bobthecow** [comment] 2016-02-25 19:49
Oh, I know why it does this. It's still stupid :)

**Comment by bobthecow** [comment] 2016-02-25 19:50
Each of those except `'0'` is an empty version of whatever type they are. Empty string? `''`. Empty array? `[]`.

`'0'` is _not_ an empty string.

**Comment by vstepanyuk** [comment] 2016-02-25 19:51
it's also:)
```
php > var_dump(empty('0'));
bool(true)
php > var_dump(empty('\0'));
bool(false)
```

**Comment by vstepanyuk** [comment] 2016-02-25 19:52
ah.. understand what you mean

**Comment by vstepanyuk** [comment] 2016-02-25 19:53
but I think php tries to cast to int, I don't understand why

**Comment by bobthecow** [comment] 2016-02-25 19:54
Because PHP made bad decisions a long time ago, and never breaks backwards compatibility.

**Comment by vstepanyuk** [comment] 2016-02-25 19:54
lol. true)

**Comment by bobthecow** [comment] 2016-02-25 20:03
the `'\0'` one is interesting. to me, that's more empty than `'0'` :P

**Comment by vstepanyuk** [comment] 2016-02-25 20:03
exactly

**Comment by bobthecow** [comment] 2016-02-25 20:09
OK. Should be fixed in `develop`. The only thing I'm not sure about is the `===` on the string comparison… I couldn't get output buffering to send the `ob_start` callback anything but a string, but i'm not positive it'd never get `null` or `false` something dumb. Could add an explicit `(string)` thunk just in case.

**Comment by vstepanyuk** [comment] 2016-02-25 22:02
Thx. Nice repl anyway

**Comment by bobthecow** [comment] 2016-02-27 19:02
The fix was released in v0.7.1. Thanks again for reporting!

**Closed by bobthecow** 2016-02-27 19:02 UTC
