### ISSUE TITLE
Not working after upgrading to PHP 7.3

### ISSUE THREAD

**Issue by dportalesr** [bobthecow/psysh#540] opened 2018-12-08 13:47 UTC
From @dciancu:
> After upgrading PHP to 7.3.0 - latest version (and Xdebug to 2.7.0beta1 latest version compatible with PHP 7.3, in case it matters), tinker is no longer working. It launches correctly but I after I input a command it just exits with no error, nothing written to log file and status code 0.

https://github.com/laravel/tinker/issues/63

I can confirm it's happening to me as well. Any input closes the REPL, no errors or messages at all.

Any ideas about how to proceed? Thanks.

**Comment by GrahamCampbell** [comment] 2018-12-08 14:31
Does it work after uninstalling xdebug?

**Comment by GrahamCampbell** [comment] 2018-12-08 14:32
xdebug 2.7.0beta1 is not actually compatible fully with php 7.3 yet. No release or even master of xdebug fully works yet.

**Comment by dciancu** [comment] 2018-12-08 14:33
@GrahamCampbell It doesn't work with xdebug disabled either

**Comment by dciancu** [comment] 2018-12-08 14:33
xdebug works very well with php 7.3 from what I have tested, has no issue with it.

**Comment by GrahamCampbell** [comment] 2018-12-08 14:33
Does it work after full uninstallation of the plugin, not just disabling?

**Comment by GrahamCampbell** [comment] 2018-12-08 14:34
> xdebug works very well with php 7.3 from what I have tested, has no issue with it.

There are various known issues documented on xdebug's github, including a failing test suite.

**Comment by dciancu** [comment] 2018-12-08 14:34
@GrahamCampbell not disabled by xdebug.enable, but removed from php.ini I meant

**Comment by dportalesr** [comment] 2018-12-09 01:03
Apparently Xdebug added support for PHP 7.3 recently
https://bugs.xdebug.org/view.php?id=1519

**Comment by bobthecow** [comment] 2018-12-09 15:19
It has something to do with forking / pcntl. I'm trying to sort it out. In the meantime, you can use PsySH by disabling pcntl support, by adding this to [your config file](https://github.com/bobthecow/psysh/wiki/Configuration):

```php
return [
  'usePcntl' => false,
];
```

**Comment by bobthecow** [comment] 2018-12-10 06:56
Ok, got it!

Homebrew-installed PHP 7.3.0 on Mojave segfaults when calling `preg_match` from a child process.

Repro:

```php
<?php

if (preg_match('/./', 'a')) echo "pre-fork works\n";

$pid = pcntl_fork();
if ($pid == -1) {
    die('fail');
} elseif ($pid) {
    if (preg_match('/./', 'a')) echo "parent works\n";
    pcntl_wait($status);
    if (pcntl_wifsignaled($status) && pcntl_wtermsig($status) == SIGSEGV) {
        die('child process segfaulted');
    }
} else {
    if (preg_match('/./', 'a')) echo "child works\n";
}
```

In PHP < 7.3, this results in:

```
pre-fork works
parent works
child works
```

But in PHP 7.3, we get:

```
pre-fork works
parent works
child process segfaulted
```

I'm not sure what the extent of this issue is. 3v4l.org doesn't have PCNTL so we can't test there. [All versions of PHP that Travis tests worked](https://travis-ci.org/bobthecow/psysh/jobs/465841499). That said, Travis is testing RC3, so it might be a bug introduced between that and the stable release?

Are y'all on Homebrew + Mojave? Can anyone repro this with other PHP 7.3 versions or sources or operating systems?

**Comment by dportalesr** [comment] 2018-12-10 07:14
> Are y'all on Homebrew + Mojave? 

Yeah.

**Comment by alphametric** [comment] 2018-12-10 09:20
Same here, Homebrew and Mojave without xdebug installed.

**Comment by chapeupreto** [comment] 2018-12-10 10:39
Just to let you know: same problem with `PHP7.3` running on `macOS High Sierra`

**Comment by bobthecow** [comment] 2018-12-10 15:20
>Just to let you know: same problem with PHP7.3 running on macOS High Sierra

Also installed via Homebrew?

**Comment by chapeupreto** [comment] 2018-12-10 15:31
> > Just to let you know: same problem with PHP7.3 running on macOS High Sierra
> 
> Also installed via Homebrew?

Yes!

**Comment by CQD** [comment] 2018-12-10 16:15
Ubuntu 16.04 + PHP 7.3 (ppa:ondre/php) + psysh 0.9.9 works fine.

No segfault when running https://github.com/bobthecow/psysh/issues/540#issuecomment-445706731

**Comment by bobthecow** [comment] 2018-12-11 04:53
It fails for both bottled and built-from-source PHP 7.3 via Homebrew.

**Comment by hulkur** [comment] 2018-12-11 08:39
In php.ini set `pcre.jit=0`

**Comment by Majkl578** [comment] 2018-12-11 14:00
@hulkur Please don't recommend people to disable JIT, report a bug to bugs.php.net instead and _only_ suggest it as a **temporary workaround**. JIT is an important performance feature.

**Comment by johnchendev** [comment] 2018-12-12 06:08
@bobthecow, Thanks for the workaround. However, I was not able to find the config file that you referenced.



> It has something to do with forking / pcntl. I'm trying to sort it out. In the meantime, you can use PsySH by disabling pcntl support, by adding this to [your config file](https://github.com/bobthecow/psysh/wiki/Configuration):
> 
> ```
> return [
>   'usePcntl' => false,
> ];
> ```

May I know how do you open this file and drop in the code you mentioned? Thanks.

Running Mac Mojave

**Comment by dportalesr** [comment] 2018-12-12 06:46
> May I know how do you open this file and drop in the code you mentioned? Thanks.

Try creating a file at `~/.config/psysh/config.php` if not already there.

**Comment by bobthecow** [comment] 2018-12-12 06:58
See also that whole page under the "your config file" link in my comment 😉

**Comment by ruudk** [comment] 2018-12-27 16:46
@bobthecow Thanks for posting the issue here. I'm using a completely different package (Resque) that also forks and crashes on preg_match. Also on Homebrew Mojave. Is there an issue on the Homebrew repository already that tracks this?

**Comment by bobthecow** [comment] 2018-12-27 17:06
Not that I know of. Wanna take it over there? :)

**Comment by ruudk** [comment] 2018-12-27 17:15
Added issue @ Homebrew https://github.com/Homebrew/homebrew-core/issues/35491

**Comment by driesvints** [comment] 2019-01-10 14:19
PHP 7.3.1 was released. Let's see if this works again when Homebrew has updated its PHP installation.

**Comment by chapeupreto** [comment] 2019-01-10 15:52
Same problem here with php `7.3.1` (installed via homebrew)

**Comment by driesvints** [comment] 2019-01-10 15:54
@chapeupreto 7.3.1 isn't available yet on Homebrew I think?

**Comment by driesvints** [comment] 2019-01-10 15:55
Nvm, just saw that it is. That's unfortunate.

**Comment by GrahamCampbell** [comment] 2019-01-10 23:33
php 7.3.1 is available on mac via phpenv

**Comment by GrahamCampbell** [comment] 2019-01-10 23:34
https://github.com/phpenv/phpenv

**Comment by ramsey** [comment] 2019-01-14 23:33
I am running PHP 7.3.0 built using [PHPBrew](https://github.com/phpbrew/phpbrew) on macOS Mojave, and I'm also having this problem. I am able to use psysh with earlier versions of PHP (7.2.11 or 7.1) built with PHPBrew and the same options.

Disabling pcntl in the config file does the trick for me.

**Comment by mkalkbrenner** [comment] 2019-01-15 08:04
I assume the problem is introduced into homebrew since the commit of https://github.com/Homebrew/homebrew-core/pull/35660

**Comment by ramsey** [comment] 2019-01-15 14:36
Does this mean I’m linking against the wrong PCRE if building PHP myself or with PHPBrew?

**Comment by chenyongze** [comment] 2019-01-16 03:50
; Enables or disables JIT compilation of patterns. This requires the PCRE

php.ini
这个改为：
pcre.jit=0

**Comment by driesvints** [comment] 2019-01-29 10:53
I believe this problem will be solved once PHP 7.3.2 & xdebug 2.7.0 are out: 

https://bugs.xdebug.org/view.php?id=1583#c4823
https://bugs.php.net/bug.php?id=77287

**Comment by driesvints** [comment] 2019-02-08 14:17
Just tested with PHP 7.3.2 (update through Homebrew) and unfortunately Tinker is still broken.

```
PHP 7.3.2 (cli) (built: Feb  5 2019 22:19:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2, Copyright (c) 1999-2018, by Zend Technologies
```

I haven't tested with a built-from-source. I believe we might need to wait until this PR is merged for Homebrew: https://github.com/Homebrew/homebrew-core/pull/36033

**Comment by GrahamCampbell** [comment] 2019-02-12 09:55
Does it work with phpenv + phpbuild?

**Comment by driesvints** [comment] 2019-02-12 09:58
@GrahamCampbell at the moment I don't have the time to try this out.

**Comment by HaroldPutman** [comment] 2019-02-19 13:05
@GrahamCampbell  I can confirm it does NOT work with phpenv + phpbuild (7.3.2) on macOS Mojave

**Comment by beschoenen** [comment] 2019-03-07 18:14
PHP 7.3.3 seems to have fixed this issue.

```
Linux defcon 4.14.78-gentoo #8 SMP Sat Nov 17 16:29:02 CET 2018 x86_64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz GenuineIntel GNU/Linux
```

```sh
➜  cli ./php psysh 
Psy Shell v0.9.9 (PHP 7.3.3 — cli) by Justin Hileman
Unable to check for updates
>>> echo "hi";
hi⏎
>>>
```

**Comment by ngocphamm** [comment] 2019-03-08 17:58
Not for PHP 7.3.3 from Homebrew though :(

**Comment by Plopix** [comment] 2019-03-08 22:20
I have still the issue too. Not fixed on PHP 7.3.3 from Homebrew

**Comment by khsing** [comment] 2019-03-09 04:22
@beschoenen not yet, still need setting `pcre.jit=0` in php.ini to make it work.

**Comment by driesvints** [comment] 2019-03-11 11:41
Can confirm the problem still isn't fixed on PHP 7.3.3 from Homebrew.

**Comment by GrahamCampbell** [comment] 2019-03-11 13:40
:/

**Comment by FariaQuitamb** [comment] 2019-04-02 09:49
https://twitter.com/paulredmond/status/1075541313532002304

this solution work form me, very fast !

**Comment by mallardduck** [comment] 2019-04-17 13:22
Just updated to `7.3.4` with brew still seeing the same issue.

**Comment by socoolbear** [comment] 2019-04-19 03:14
i have same issue too. ( php 7.3.4 , installed homebrew )

```
➜  temp ✗ php -v
PHP 7.3.4 (cli) (built: Apr  8 2019 10:21:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.4, Copyright (c) 1999-2018, by Zend Technologies
➜  cr-web git:(feature/deck_build) ✗ php artisan tinker
Psy Shell v0.9.9 (PHP 7.3.4 — cli) by Justin Hileman
>>>
>>>
>>> echo 1;
➜  temp ✗
```

**Comment by driesvints** [comment] 2019-04-19 09:58
FWIW I really believe this needs to be taken up with Homebrew and this issue should be closed. It's obvious that it's specifically Homebrew that has a faulty install.

**Comment by ramsey** [comment] 2019-04-19 14:25
I'm not using PHP from Homebrew. I've installed PHP from source, and I'm having this issue. Does a library I've installed from Homebrew and linked against when building PHP have the issue?

**Comment by driesvints** [comment] 2019-04-19 14:29
@ramsey hmm, I was mistaken then. I only saw reports from people installing through Homebrew so far. You don't have any binaries from PHP installed? What's your output for `brew list`?

**Comment by ramsey** [comment] 2019-04-19 14:36
Here's my PHP configure command:

```
'./configure' \
'--cache-file=/Users/ramsey/.php/cache/config.cache' \
'--prefix=/Users/ramsey/.php/php/php-7.3.0' \
'--with-config-file-path=/Users/ramsey/.php/php/php-7.3.0/etc' \
'--with-config-file-scan-dir=/Users/ramsey/.php/php/php-7.3.0/var/db' \
'--disable-all' \
'--enable-session' \
'--enable-short-tags' \
'--enable-bcmath' \
'--with-bz2=/usr/local/opt/bzip2' \
'--enable-calendar' \
'--enable-cli' \
'--enable-ctype' \
'--enable-fileinfo' \
'--enable-filter' \
'--enable-shmop' \
'--enable-sysvsem' \
'--enable-sysvshm' \
'--enable-sysvmsg' \
'--enable-json' \
'--enable-mbregex' \
'--enable-mbstring' \
'--with-mhash=/usr/local' \
'--enable-pcntl' \
'--with-pcre-regex' \
'--with-pcre-dir=/usr/local' \
'--enable-pdo' \
'--with-sqlite3' \
'--with-pdo-sqlite' \
'--with-mysqli=mysqlnd' \
'--with-pdo-mysql=mysqlnd' \
'--with-mysql-sock=/tmp/mysql.sock' \
'--enable-phar' \
'--enable-posix' \
'--with-libedit=/usr/local/opt/libedit' \
'--enable-sockets' \
'--with-tidy' \
'--enable-tokenizer' \
'--enable-dom' \
'--enable-libxml' \
'--enable-simplexml' \
'--enable-xml' \
'--enable-xmlreader' \
'--enable-xmlwriter' \
'--with-xsl' \
'--with-libxml-dir=/usr/local/opt/libxml2' \
'--with-curl=/usr/local/opt/curl' \
'--enable-zip' \
'--with-openssl=/usr/local/opt/openssl' \
'--with-gmp=/usr/local' \
'--with-iconv=/usr/local/opt/libiconv' \
'--enable-opcache' \
'--with-zlib=/usr/local/opt/zlib' \
'--disable-intl' \
'--without-icu-dir' \
"$@"
```

And here's the output of `brew list`:

```
$ brew list
ack				jemalloc			openssl
ant				jpeg				openssl@1.1
ant-contrib			jq				ossp-uuid
autoconf			libedit				packer
automake			libev				packer-completion
aws-sam-cli			libevent			pcre
awscli				libexif				perl
bison				libffi				pkg-config
boost				libiconv			popt
bzip2				libidn2				python
c-ares				libimobiledevice		python@2
cmake				libmpc				qrencode
cocoapods			libplist			rbenv
coreutils			libpng				re2c
curl				libpq				readline
dart				libsass				ruby
editorconfig			libsodium			ruby-build
exif				libssh2				s3cmd
exiv2				libtasn1			sassc
findutils			libtiff				saxon-b
freetype			libtool				sqlite
gcc				libunistring			sshfs
gdb				libusb				telnet
gdbm				libxml2				tidy-html5
gettext				libyaml				tmux
ghostscript			libzip				tree
git				little-cms2			unixodbc
glib				lua				unrar
gmp				make				unzip
gnu-sed				mas				usbmuxd
gnu-tar				maven				vim
google-authenticator-libpam	mcrypt				watchman
gzip				media-info			webp
highlight			mhash				wget
icu4c				minisign			whois
ideviceinstaller		mpfr				with-readline
idnits				mysql-client			xz
ios-deploy			nghttp2				yarn
isl				node				zlib
jansson				oniguruma			zsh
```

**Comment by driesvints** [comment] 2019-04-19 14:41
@ramsey is `--with-pcre-dir` even needed now that pcre2 comes bundled with php 7.3? Can you try to recompile without this option?

**Comment by driesvints** [comment] 2019-04-19 14:42
Also see: https://www.php.net/manual/en/pcre.installation.php#123134

**Comment by GrahamCampbell** [comment] 2019-04-19 15:48
Surely it's the `--enable-jit` option which is breaking everything?

**Comment by mallardduck** [comment] 2019-04-19 16:18
@GrahamCampbell I may be wrong about how I'm reading your comment, but the brew formula doesn't seem to include that option. So should we attempt a build with that option included then?

I'm not sure if it was buried and forgotten or written off as not being related. However, one of the Homebrew issues linked to this PHP core bug: https://bugs.php.net/bug.php?id=77260
So there's another explanation behind the issue if that bug is indeed related.

**Comment by ramsey** [comment] 2019-04-19 16:46
The brew formula for pcre2 does include `--enable-jit`. https://github.com/Homebrew/homebrew-core/blob/master/Formula/pcre2.rb

**Comment by mallardduck** [comment] 2019-04-19 16:50
@ramsey Ahh, my fault - didn't realize that was a pcre2 option not PHP.

However, wouldn't that mean PHP cannot use JIT for PCRE anymore? If so, then removing that from the `pcre2` build would have the same end result of `pcre.jit=0` workaround.

**Comment by ramsey** [comment] 2019-04-19 16:54
I just build PHP without using `--with-pcre-dir`, so presumably, it's using the bundled pcre2 library, but this issue is still occurring.

Here's some more information...

```
$ php --ri pcre

pcre

PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 10.32 2018-09-10
PCRE Unicode Version => 11.0.0
PCRE JIT Support => enabled
PCRE JIT Target => x86 64bit (little endian + unaligned)

Directive => Local Value => Master Value
pcre.backtrack_limit => 1000000 => 1000000
pcre.recursion_limit => 100000 => 100000
pcre.jit => 1 => 1
```

Updated PHP configure command:

```
'./configure' \
'--cache-file=/Users/ramsey/.php/cache/config.cache' \
'--prefix=/Users/ramsey/.php/php/php-7.3.4' \
'--with-config-file-path=/Users/ramsey/.php/php/php-7.3.4/etc' \
'--with-config-file-scan-dir=/Users/ramsey/.php/php/php-7.3.4/etc/php.d' \
'--disable-all' \
'--enable-session' \
'--enable-short-tags' \
'--with-pcre-regex' \
'--enable-bcmath' \
'--with-bz2=/usr/local/opt/bzip2' \
'--enable-calendar' \
'--enable-cli' \
'--enable-ctype' \
'--enable-fileinfo' \
'--enable-filter' \
'--enable-shmop' \
'--enable-sysvsem' \
'--enable-sysvshm' \
'--enable-sysvmsg' \
'--enable-json' \
'--enable-mbregex' \
'--enable-mbstring' \
'--with-mhash=/usr/local' \
'--enable-pcntl' \
'--enable-pdo' \
'--with-sqlite3' \
'--with-pdo-sqlite' \
'--with-mysqli=mysqlnd' \
'--with-pdo-mysql=mysqlnd' \
'--with-mysql-sock=/tmp/mysql.sock' \
'--enable-phar' \
'--enable-posix' \
'--with-libedit=/usr/local/opt/libedit' \
'--enable-sockets' \
'--with-tidy' \
'--enable-tokenizer' \
'--enable-dom' \
'--enable-libxml' \
'--enable-simplexml' \
'--enable-xml' \
'--enable-xmlreader' \
'--enable-xmlwriter' \
'--with-xsl' \
'--with-libxml-dir=/usr/local/opt/libxml2' \
'--with-curl=/usr/local/opt/curl-openssl' \
'--enable-zip' \
'--with-openssl=/usr/local/opt/openssl' \
'--with-gmp=/usr/local' \
'--with-iconv=/usr/local/opt/libiconv' \
'--enable-opcache' \
'--with-zlib=/usr/local/opt/zlib' \
'--disable-intl' \
'--without-icu-dir' \
"$@"
```

**Comment by ramsey** [comment] 2019-04-19 17:37
Here's a screen recording to show the behavior I'm seeing. You can also see that there are no errors in the error logs.

![psysh](https://user-images.githubusercontent.com/42941/56435916-c5d67880-629f-11e9-8e70-618abc0258c2.gif)

**Comment by mallardduck** [comment] 2019-04-19 18:40
@ramsey The lack of logging is expected, the behavior we're seeing is a hard crash. PHP won't be able to log this directly.

**Comment by amitavroy** [comment] 2019-04-27 05:08
> > May I know how do you open this file and drop in the code you mentioned? Thanks.
> 
> @johnchendev Try creating a file at `~/.config/psysh/config.php` if not already there.
> 
> ```
> <?php
> return [
>   'usePcntl' => false,
> ];
> ```
> 
> That's it.

This worked for me. Thanks a lot.

**Comment by chapeupreto** [comment] 2019-05-02 22:14
Unfortunately, it's **not** working with PHP `7.3.5` installed via *homebrew*.

**Comment by mallardduck** [comment] 2019-05-02 22:51
Just wanted to say I appreciate @bobthecow keeping this open, even tho at this point it seems clear to be a platform issue. The config based solution works as a 'fix', but the issue is pervasive beyond psysh so not a real/full solution.

Until the underlying issue is fixed then other applications and use cases will still be affected. Perhaps more important, it means that a development environment is even less similar to production environments.

**Comment by akeebismail** [comment] 2019-06-03 09:07
> As a workaround:
> 
> In php.ini set `pcre.jit=0`
> 
> Note comment below.

this solve the problem for now

**Comment by ihorvorotnov** [comment] 2019-06-05 16:05
Brew's PHP 7.3.6 - still crashes.

**Comment by miken32** [comment] 2019-06-14 18:23
For the record, I had this problem with PHP 7.2.19 – the suggested fix of disabling the pcntl extension in psysh config fixed it for me. And I don't use Homebrew at all.

**Comment by mallardduck** [comment] 2019-06-14 18:26
@miken32 And you're on a Mac, PC, or Linux?

**Comment by miken32** [comment] 2019-06-14 18:51
@mallardduck sorry, edited my comment. MacOS.

**Comment by JacquesvanWyk** [comment] 2019-07-02 14:53
> > May I know how do you open this file and drop in the code you mentioned? Thanks.
> 
> @johnchendev Try creating a file at `~/.config/psysh/config.php` if not already there.
> 
> ```
> <?php
> return [
>   'usePcntl' => false,
> ];
> ```
> 
> That's it.

That worked for me. Thank you

**Comment by ngocphamm** [comment] 2019-07-07 11:25
It looks like this is fix with PHP 7.3.7 Homebrew. At least for me, I don't need the line in `config.php` file anymore.

**Comment by welenofsky** [comment] 2019-07-08 17:20
> It looks like this is fix with PHP 7.3.7 Homebrew. At least for me, I don't need the line in `config.php` file anymore.

I just tried upgrading from 7.3.5 -> 7.3.7 and it did not resolve the issue for me :(

**Comment by mallardduck** [comment] 2019-07-08 18:05
Same issue as @welenofsky, not working after upgrading. I wonder if @ngocphamm has something setup differently on their machine?

**Comment by ngocphamm** [comment] 2019-07-09 01:59
I'm not too sure. This is my `.config/psysh/config.php`. PHP was upgraded with `brew upgrade` (update all outdated brews in my system)

```
return array(
    'historySize' => 200,
    'eraseDuplicates' => true,
    //'usePcntl' => false,
);
```

**Comment by mallardduck** [comment] 2019-07-09 12:40
@ngocphamm I wonder if it has something to do with other system configurations though. Like the Mac OS X version you're using, PCRE version, things like that maybe?

I'm also forgetting and wonder if this is isolated to Mac's or if it would also affect other Unix based systems?

**Comment by ngocphamm** [comment] 2019-07-09 13:16
I'm using latest macOS 10.14.5, with both `pcre` and `pcre2` installed via Homebrew, with version `8.43`, and `10.33`, respectively.

**Comment by welenofsky** [comment] 2019-07-09 19:53
> I'm using latest macOS 10.14.5, with both `pcre` and `pcre2` installed via Homebrew, with version `8.43`, and `10.33`, respectively. And `php` actually uses `pcre` according to this
> 
> ```
> ~ »  brew uses pcre --installed
> cairo                 glib                  imagemagick           nginx                 shared-mime-info      zsh
> ffmpeg                harfbuzz              libass                php                   the_silver_searcher
> ~ »  brew uses pcre2 --installed
> fish                                                                ripgrep
> ```

I am using the same macOS version (10.14.5) and same PCRE/PCRE2 versions as you listed. Wondering what the difference could be.

**Comment by bobthecow** [comment] 2019-07-10 02:19
>I'm also forgetting and wonder if this is isolated to Mac's or if it would also affect other Unix based systems?

It has been reported on Linux systems as well.

**Comment by zeshan77** [comment] 2019-10-02 07:52
> **Update: as discussed below, this is a bug in Homebrew/macOS/PHP/pcntl. It should really be worked around by disabling `pcre.jit` in your `php.ini`.**
> 
> It has something to do with forking / pcntl. I'm trying to sort it out. In the meantime, you can use PsySH by disabling pcntl support, by adding this to [your config file](https://github.com/bobthecow/psysh/wiki/Configuration):
> 
> ```
> return [
>   'usePcntl' => false,
> ];
> ```

It worked for me. Thanks for the workaround!

**Comment by mk-conn** [comment] 2019-10-30 11:03
Just upgraded to PHP 7.3.11 and psysh is working again

**Comment by ramsey** [comment] 2019-10-30 14:34
I can confirm the same. I do not need to set `usePcntl` to `false` when running psysh on PHP 7.3.11.

**Comment by driesvints** [comment] 2019-10-30 19:27
Same for me. Seems to be finally fixed 👍

**Comment by zymawy** [comment] 2019-10-30 20:20
Confirmed ! 🥇

**Comment by chapeupreto** [comment] 2019-10-30 21:44
All good here (PHP 7.3.11)

**Comment by welenofsky** [comment] 2019-10-31 03:23
Confirmed here as well!

**Comment by bobthecow** [comment] 2019-12-01 07:42
Working for me as well.

I'm going to close this, but leave it pinned, so people can find it if they need to.

**Closed by bobthecow** 2019-12-01 07:42 UTC
