### ISSUE TITLE
When `require`/`require_once` fails REPL closes

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#383] opened 2017-06-05 09:02 UTC
```
PS C:\nginx\html\projects\eldoria-ticketsystem\src> psysh
Psy Shell v0.8.6 (PHP 7.1.5 — cli) by Justin Hilemanan
How are you doing sir? c: [custom header message]
>>> require 'vendor/autoload.php';
PHP Warning:  Uncaught Psy\Exception\ErrorException: PHP warning:  require(vendor/autoload.php): failed to open stream: No such file or
 directory on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(838): Psy\Exception\ErrorException::throwException(2, 'req
uire(vendor/...', 'C:\\Users\\Jens\\A...', 1)
#1 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): Psy\Shell->handleErro
r(2, 'require(vendor/...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): require()
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\
Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(328): Psy\ExecutionLoop\Loop->run(Objec in (null) on line
1
PHP Stack trace:
PHP   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
PHP   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
PHP   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:252
PHP   4. Symfony\Component\Console\Application->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:292
PHP   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:130
PHP   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:328
PHP   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146
PHP   8. eval() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:90

Warning: Uncaught Psy\Exception\ErrorException: PHP warning:  require(vendor/autoload.php): failed to open stream: No such file or dire
ctory on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(838): Psy\Exception\ErrorException::throwException(2, 'req
uire(vendor/...', 'C:\\Users\\Jens\\A...', 1)
#1 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): Psy\Shell->handleErro
r(2, 'require(vendor/...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): require()
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\
Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(328): Psy\ExecutionLoop\Loop->run(Objec in (null) on line
1

Call Stack:
    0.0005     392904   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
    0.0188    1440640   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
    0.1074    5159168   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:252
    0.1131    5309232   4. Symfony\Component\Console\Application->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy
\Shell.php:292
    0.1851    5310760   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:130
    0.1886    5330984   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:328
    0.1887    5331944   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\
Loop.php:146
   64.9989    5492672   8. eval('return require 'vendor/autoload.php';') C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Ps
y\ExecutionLoop\Loop.php:90

PHP Fatal error:  Unknown: Failed opening required 'vendor/autoload.php' (include_path='.;c:\php\includes') in C:\Users\Jens\AppData\Ro
aming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1
PHP Stack trace:
PHP   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
PHP   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
PHP   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:252
PHP   4. Symfony\Component\Console\Application->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:292
PHP   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:130
PHP   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:328
PHP   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146
PHP   8. eval() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:90

Fatal error: Unknown: Failed opening required 'vendor/autoload.php' (include_path='.;c:\php\includes') in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1

Call Stack:
    0.0005     392904   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
    0.0188    1440640   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
    0.1074    5159168   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:252
    0.1131    5309232   4. Symfony\Component\Console\Application->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy
\Shell.php:292
    0.1851    5310760   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:130
    0.1886    5330984   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:328
    0.1887    5331944   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\
Loop.php:146
   64.9989    5492672   8. eval('return require 'vendor/autoload.php';') C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Ps
y\ExecutionLoop\Loop.php:90

**Comment by bobthecow** [comment] 2017-06-08 10:57
See #176 for why this is a bit complicated to fix, but I just pushed a workaround to the `develop` branch and it'll go out in the next stable release.

Closing as a duplicate of #175

**Closed by bobthecow** 2017-06-08 10:57 UTC
