### ISSUE TITLE
Ctrl-C: Cancel current line instead of quitting

### ISSUE THREAD

**Issue by richarddewit** [bobthecow/psysh#431] opened 2017-10-18 11:43 UTC
Is it possible to implement the action of canceling the current typed line and returning to a new prompt-line when I press Ctrl-C? Now it (frustratingly) quits the application completely.

**Observed behaviour**

``` bash
$ psysh
Psy Shell v0.8.11 (PHP 7.1.10 — cli) by Justin Hileman
>>> serialize(['a' => 'test'])
=> "a:1:{s:1:"a";s:4:"test";}"
>>> serialize(['a' =>^C     # Oh no, I didn't mean to type this
$                           # application has exited
```

**"Expected" behaviour**

``` bash
$ psysh
Psy Shell v0.8.11 (PHP 7.1.10 — cli) by Justin Hileman
>>> serialize(['a' => 'test'])
=> "a:1:{s:1:"a";s:4:"test";}"
>>> serialize(['a' =>^C     # Oh no, I didn't mean to type this
>>>                         # back to prompt
```
You can still exit using Ctrl-D

**Comment by kubk** [comment] 2017-12-04 20:50
You can use Ctrl+U to clear up to the beginning. This shortcut works fine for me in Bash and Zsh. And for *nix systems is expected behavior to "kill whatever you are running" using Ctrl+C

**Comment by bobthecow** [comment] 2017-12-04 21:25
But for interactive shells, Ctrl+C to kill the line is common. Then (sometimes) a second Ctrl+C to kill the shell.

**Comment by filips123** [comment] 2018-10-29 11:15
When Ctrl+C is pressed, program should check the current line. If it is not empty, it should cancel it. If it is empty, it should exit the program.

**Comment by phil-s** [comment] 2018-10-30 22:20
Personally I feel that Ctrl+D at an empty prompt is a sufficiently standard Exit command, and I would be in favour of Ctrl+C cancelling input, but not exiting the program.  Just like Unix shells, in other words.

Exiting contextually, if there is no input, just sounds too easy to do accidentally.

**Comment by jchook** [comment] 2018-12-16 03:52
I agree and believe this issue should be closed by adding more documentation surrounding <kbd>Ctrl</kbd> + <kbd>D</kbd>.

**Comment by bobthecow** [comment] 2019-04-22 00:33
Closing as a duplicate of #154

**Closed by bobthecow** 2019-04-22 00:33 UTC
Labels: enhancement

**Comment by Criziz21** [comment] 2023-01-15 14:42
To escape Shift + q
