### ISSUE TITLE
Installable via Phive?

### ISSUE THREAD

**Issue by courtney-miles** [bobthecow/psysh#575] opened 2019-11-10 00:04 UTC
The installation guide says Psysh is installable with Phive using the following command:

```bash
sudo phive install -g bobthecow/psysh
```

For myself, this command return a bunch of warnings and finally an error that no Phar files could be found.

```
Phive 0.13.2 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
[WARNING]  bobthecow/psysh 0.9.9: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.8: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.7: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.6: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.5: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.4: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.3: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.2: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.1: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.9.0: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.18: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.17: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.16: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.15: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.14: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.13: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.12: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.11: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.10: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.9: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.8: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.7: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.6: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.5: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.4: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.3: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.2: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.1: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.8.0: No downloadable PHAR 
[WARNING]  bobthecow/psysh 0.7.2: No downloadable PHAR 
[ERROR]    No matching release found!
```

Is the Phive installation method supported?

**Comment by bobthecow** [comment] 2019-12-01 07:39
It's not currently installable via Phive. It should be on the next release.

**Comment by bobthecow** [comment] 2020-05-03 15:58
Closing as a duplicate of #489

**Closed by bobthecow** 2020-05-03 15:58 UTC
Labels: duplicate
