### ISSUE TITLE
Warning: unable to select [4]: Interrupted system call

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#494] opened 2018-05-12 06:45 UTC
```
[Fri May 11 21:54:12 2018] [hphp] [32245:7fa6db5fb200:0:000002] [] 
Warning: unable to select [4]: Interrupted system call in /srv/mediawiki/php-1.32.0-wmf.3/vendor/psy/psysh/src/Psy/ExecutionLoop/ForkingLoop.php on line 57
RuntimeException with message 'Error waiting for execution loop.'
[Fri May 11 21:54:21 2018] [hphp] [32348:7fa6db5fb200:0:000002] [] 
Notice: fwrite(): send of 3290537 bytes failed with errno=32 Broken pipe in /srv/mediawiki/php-1.32.0-wmf.3/vendor/psy/psysh/src/Psy/ExecutionLoop/ForkingLoop.php on line 83
```
After exiting, the terminal is all messed up (most keys do not work).

Same as #268 presumably, and a number of other projects seem to have the same problem (e.g. symfony/symfony#6540, PHPMailer/PHPMailer#1227). Apparently `stream_select` returns false when the process receives a signal, even when that signal shouldn't terminate the process.

**Comment by bobthecow** [comment] 2018-05-20 15:58
I haven't been able to reproduce this. Since you've got a consistent repro, do you mind testing this as a workaround?

```diff
diff --git a/src/ExecutionLoop/ProcessForker.php b/src/ExecutionLoop/ProcessForker.php
index 1a5bb7a..f7f3966 100644
--- a/src/ExecutionLoop/ProcessForker.php
+++ b/src/ExecutionLoop/ProcessForker.php
@@ -65,9 +65,19 @@ class ProcessForker extends AbstractListener
             $read   = [$down];
             $write  = null;
             $except = null;
-            if (stream_select($read, $write, $except, null) === false) {
-                throw new \RuntimeException('Error waiting for execution loop');
-            }
+
+            do {
+                $n = stream_select($read, $write, $except, null);
+
+                if ($n === 0) {
+                    throw new \RuntimeException('Process timed out waiting for execution loop');
+                } elseif ($n === false) {
+                    $err = error_get_last();
+                    if (!isset($err['message']) || stripos($err['message'], 'interrupted system call') === false) {
+                        throw new \RuntimeException('Error waiting for execution loop');
+                    }
+                }
+            } while ($n < 1);
 
             $content = stream_get_contents($down);
             fclose($down);
```

**Comment by bobthecow** [comment] 2018-05-27 14:49
poke @tgr :)

**Comment by tgr** [comment] 2018-05-28 02:10
Thanks for looking into it!

We are using PsySH 0.8.11 and I can only reproduce the error in production so I backported the patch to b193cd020:src/Psy/ExecutionLoop/ForkingLoop.php. After applying it, I still get the *Interrupted system call* warning but it doesn't break PsySH anymore - I get back the command prompt, and there is no warning on any subsequent commands.

**Comment by bobthecow** [comment] 2018-05-29 03:30
Great, thanks!

I've pushed the fix to `develop` and it'll be out in the next stable release.

Y'all should update to v0.9 ;)

**Comment by tgr** [comment] 2018-05-29 06:58
Thanks a lot! Will update when the patch is released.

Is there a way to suppress the warning message? Not a big deal but slightly confusing. Maybe just do `@stream_select` and put the error message in the exception when it's not ignored?

**Comment by bobthecow** [comment] 2018-05-29 08:07
something like …

```diff
diff --git a/src/ExecutionLoop/ProcessForker.php b/src/ExecutionLoop/ProcessForker.php
index bbf6225..7cf71b1 100644
--- a/src/ExecutionLoop/ProcessForker.php
+++ b/src/ExecutionLoop/ProcessForker.php
@@ -67,7 +67,7 @@ class ProcessForker extends AbstractListener
             $except = null;
 
             do {
-                $n = stream_select($read, $write, $except, null);
+                $n = @stream_select($read, $write, $except, null);
 
                 if ($n === 0) {
                     throw new \RuntimeException('Process timed out waiting for execution loop');
@@ -76,7 +76,7 @@ class ProcessForker extends AbstractListener
                 if ($n === false) {
                     $err = error_get_last();
                     if (!isset($err['message']) || stripos($err['message'], 'interrupted system call') === false) {
-                        throw new \RuntimeException('Error waiting for execution loop');
+                        throw new \RuntimeException(sprintf('Error waiting for execution loop: %s', $err['message']));
                     }
                 }
             } while ($n < 1);
```

I'm open to this. I haven't seen what the actual experience is like, but if it's a warning that isn't actionable, and doesn't have any effect on the session, then i'm all for suppressing it.

**Comment by tgr** [comment] 2018-05-30 14:26
Some people from Wikimedia ops looked into the issue, and apparently this is somehow caused by HHVM's pre-created threads - the error does not happen when using Zend or `hhvm.server.light_process_count = 0`.  Which is a fine workaround for us. #268 is with Zend though, so the patch is still useful in other circumstances.

I am not sure about suppressing the error - in general it's not a good idea, but the error is confusing and not really useful without at least knowing what kind of signal it was.

**Comment by bobthecow** [comment] 2018-05-30 20:27
It does seem like a pretty worthless warning. It's not actionable, and really, the user doesn't care if it took us two tries to stream_select. I'll add the change above.

**Comment by bobthecow** [comment] 2018-05-31 06:37
Okay, we're now suppressing the stream select error if it's an interrupted system call, and throwing it as a runtime exception otherwise.

**Comment by tgr** [comment] 2018-05-31 12:44
Awesome, thanks a lot!

**Closed** 2018-06-02 16:40 UTC
Labels: done
