### ISSUE TITLE
How to ad scope variable from custom command

### ISSUE THREAD

**Issue by dmitriyshashkin** [bobthecow/psysh#504] opened 2018-06-09 15:17 UTC
I want to add a custom command that would boot my application and make the service container available through "container" variable. Checked the code, looked up a couple of the implementations of the integration of psysh with different frameworks, but still wasn't able to figure out how to do this. I'd appreciate any help. Thanks!

**Comment by dmitriyshashkin** [comment] 2018-06-11 08:28
Thank you very much for such a detailed explanation. I've seen the way others do it, but my idea was not to create a new entry point and also boot my kernel only after I call the custom command. I thought that doing something like `$this->getApplication()->setScopeVariables(['container' => $container]);` inside my command should suffice. Do I understand correctly that setScopeVariables call has no effect after the shell has been already loaded?

**Comment by bobthecow** [comment] 2018-07-23 06:47
>Do I understand correctly that setScopeVariables call has no effect after the shell has been already loaded?

It is _supposed_ to work, though not because it's intended to be used like that 🙂

Unfortunately there was a regression in v0.9.4 which kept scope variables set that way from being propagated back into the current execution scope. They were still available to other commands, but not to user input. I just pushed a fix (003c71b5f7a5a8dbfd228388846637f2157dbad1) which will go out in the next release.

**Comment by dmitriyshashkin** [comment] 2018-07-27 11:52
Fantastic! I'll check it out

**Closed as completed** 2018-08-25 18:24 UTC
