### ISSUE TITLE
Fatal error and crash when dumping var

### ISSUE THREAD

**Issue by jhdxr** [bobthecow/psysh#570] opened 2019-09-08 18:01 UTC
env:
* psysh: 0.9.9
* php: 7.2.14
* os: win 10

codes to reproduce:
```
>>> class aaaaa extends DirectoryIterator{public function __construct($a, $b){}}
>>> new aaaaa(1,2);

Fatal error: SplFileInfo::getATime(): Object not initialized in C:\Users\me\AppData\Roaming\Composer\vendor\symfony\var-dumper\Caster\SplCaster.php on line 113
```

while these codes work in php shell:
```
λ php -a
Interactive shell

php > class aaaaa extends DirectoryIterator{public function __construct($a, $b){}}
php >  new aaaaa(1,2);
php > $a= new aaaaa(1,2);
php > var_dump($a);
object(aaaaa)#1 (1) {
  ["pathName":"SplFileInfo":private]=>
  string(0) ""
}
```

I know it may not make sense to write such code, but I would expect psysh not crash at least.

**Comment by bobthecow** [comment] 2019-10-04 04:43
This is probably a bug in VarDumper's SplCaster. I don't have a Windows machine handy to test it on, and I can't reproduce it on my Mac or Linux boxes.

cc @nicolas-grekas any ideas?

**Comment by nicolas-grekas** [comment] 2019-10-04 07:43
Should be fixed by https://github.com/symfony/symfony/pull/33841

**Closed** 2019-11-23 20:59 UTC
