### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#222] opened 2015-08-04 11:37 UTC
You seem to have revoked our access token @bobthecow?

**Comment by bobthecow** [comment] 2015-08-06 04:08
Everything should be wired up and running again. Any idea why this one fails on StyleCI but work (with equivalent config) locally?

https://styleci.io/analyses/86ngn8

**Comment by GrahamCampbell** [comment] 2015-08-06 17:28
Probably because we don't use the same version of php-cs-fixer that's public. Ours is better. :P

**Comment by GrahamCampbell** [comment] 2015-08-06 17:29
This looks to be psr2 related though.

**Comment by GrahamCampbell** [comment] 2015-08-06 17:29
PSR2 doesn't allow those spaces there.

**Comment by bobthecow** [comment] 2015-08-10 20:48
PSR2 is a jerk.

**Comment by GrahamCampbell** [comment] 2015-08-10 20:49
You could turn off the function argument fixer?

**Comment by bobthecow** [comment] 2015-08-23 16:55
I re-read that section of PSR-2, and I think I disagree.

> In the argument list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.

I read this as "…there MUST be (at least) one space after each comma." Whoever wrote that check reads it as "…there MUST be (exactly) one space after each comma." You could make an argument about what was intended by that statement, but it does allow both interpretations. And when a standard is ambiguous, it has to allow all reasonable interpretations.

Where do I open a bug report for this argument fixer? :)

**Comment by GrahamCampbell** [comment] 2015-08-23 22:13
> In the argument list, there MUST NOT be a space before each comma, and there MUST be one space after each comma.

That means exactly one. It's just badly worded. If it meant one more more, I think it would have said "more than one".

**Comment by bobthecow** [comment] 2015-09-09 08:44
I disagree. Anyway, it's kind of a moot point, since it's highly unlikely they'll change it, and it's highly unlikely either of us will convince the other that their interpretation is correct. Closing for now ;)

**Closed by bobthecow** 2015-09-09 08:44 UTC
