### ISSUE TITLE
cannot use any psysh command

### ISSUE THREAD

**Issue by chapeupreto** [bobthecow/psysh#705] opened 2022-02-03 01:24 UTC
I have installed _psysh_ on my system using the command `composer global require psy/psysh:@stable` and, odd enough, I cannot use any of its command. Image below shows what's happening:

![Screenshot from 2022-02-02 22-16-35](https://user-images.githubusercontent.com/834048/152265061-93669753-ee88-498a-bb88-b24d630ed487.png)

Here is the output of `lsb_release -a`:

```console
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Any ideas?

**Comment by bobthecow** [comment] 2022-02-03 01:37
This is the same as #703 and #704, and is caused by a backwards compatibility break in the latest version(s) of symfony/console. [The fix has been merged](https://github.com/symfony/symfony/pull/45240), and should be in the next release. Until then, you can work around it by pinning to `symfony/console:6.0.2`:

```
composer global require symfony/console:6.0.2
```

**Comment by chapeupreto** [comment] 2022-02-03 02:22
I did what you told me to do and it's working fine now.

I'm closing this issue then!

Thanks a lot bob!

**Comment by bobthecow** [comment] 2022-02-03 07:14
I'm keeping this issue open and pinned until the next symfony/console release to help everyone else out :)

**Comment by tgr** [comment] 2022-02-09 07:55
Also affects Symfony 5.4.3. Looking at their release logs, probably 5.3.14 and 4.4.37 as well.

**Comment by bobthecow** [comment] 2022-02-09 13:56
Yep, all supported versions are affected on their latest point release. In this case the report was about symfony 6.0 but good call, I should have answered more generically :)

**Comment by bobthecow** [comment] 2022-02-09 19:56
I was considering that, but wouldn't it be as likely to resolve by downgrading psysh (where the issue still exists) as downgrading symfony?

**Comment by bobthecow** [comment] 2022-02-09 20:10
@Seldaek is my understanding correct? Is there a way to solve for this from the PsySH end without yanking all currently released versions with this conflict?

**Comment by Seldaek** [comment] 2022-02-09 20:19
Yes that is correct. I don't think you can do much here except pin an issue with a clear workaround explainer in the top post, then wait it out.

**Comment by bobthecow** [comment] 2022-02-09 20:31
Yeah, that makes sense. Unfortunately this gets reported as a bug in a bunch of things built on PsySH and _they_ keep having to investigate the issue themselves so it'd be cool if we could reliably solve it with composer.json. 

If I do the conflict thing, will it _sometimes_ work out the way we'd like? Is it still worth doing for the people it helps?

**Comment by Seldaek** [comment] 2022-02-09 20:55
It may help in rare cases I suppose and it doesn't hurt to try.. At least you prevent those buggy versions from being used from now on. But I can also see that doing nothing is valid.

The key takeaway here IMO is everyone needs to test more aggressively against dev versions of their deps to catch these regressions before they are released. I've been meaning to blog about this for a while, maybe I should :p

**Comment by bobthecow** [comment] 2022-02-10 00:10
Yeah that could be your key takeaway. Orrrrr that Symfony should run tests against their biggest dependents so they don't push backwards compatibility breaks on point releases could be the key takeaway ;)

**Comment by bobthecow** [comment] 2022-02-10 05:48
For what it's worth, I _do_ test `@dev` dependencies, and they did fail [for a single build](https://github.com/bobthecow/psysh/actions/runs/1749109663), about 48 hours before the release(s) in question were tagged. No, I didn't notice.

But I just randomly happened to push a bugfix in the window where it would have caught it. Maybe I need to run a dev dependency test on a cron job so I can stay more on top of things?

**Comment by bobthecow** [comment] 2022-02-28 13:56
As of todays Symfony release(s), we've got green builds again :) 

https://github.com/bobthecow/psysh/runs/5360469314

**Comment by bobthecow** [comment] 2022-02-28 15:44
Annnnnd we're fixed. Thanks for your patience!

**Closed by bobthecow** 2022-02-28 15:44 UTC
