### ISSUE TITLE
Namespaced constant in array key not accepted

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#495] opened 2018-05-12 08:46 UTC
```
>>> sudo $informationData = $dataCollector->selectInformationTemplate( $templateData[CommonsMetadata\TemplateParser::INFORMATION_FIELDS_KEY] )
PhpParser\Error with message 'Syntax error, unexpected T_NS_SEPARATOR, expecting T_STRING on line 1'

>>> $x = CommonsMetadata\TemplateParser::INFORMATION_FIELDS_KEY
=> "informationFields"
>>> sudo $informationData = $dataCollector->selectInformationTemplate( $templateData[$x] )
=> [...]
```

**Comment by bobthecow** [comment] 2018-05-20 15:08
I'm not able to reproduce this. Can you share a minimal test case?

```php
namespace A {
    class B {
        const C = 'see';
    }
}

class D {
    private function e($f) {
        return [$f];
    }
}

$g = [];
$g[A\B::C] = 'c';

$d = new D();
sudo $h = $d->e($g[A\B::C]); // => ['c']
```

**Comment by tgr** [comment] 2018-05-29 07:50
I've seen this in Wikipedia production and the PsySH version there is quite old. I'll see if the error sticks after the upgrade.

**Comment by bobthecow** [comment] 2018-10-20 16:41
(nudge)

did you come up with a test case?

**Comment by bobthecow** [comment] 2019-01-19 17:53
Closing since I’m still not able to repro. Feel free to re-open with a test case!

**Closed by bobthecow** 2019-01-19 17:53 UTC
