### ISSUE TITLE
Psysh ignores composer autoloader?

### ISSUE THREAD

**Issue by ostrolucky** [bobthecow/psysh#640] opened 2020-06-01 13:52 UTC
```
❯ pwd
/Users/gabriel.ostrolucky/Documents/enrola/project
❯ cat test.php
<?php

require 'vendor/autoload.php';

$uri = new \GuzzleHttp\Psr7\Uri('action=add');
echo $uri;
❯ php test.php
action=add%                                                                                                        
❯ psysh
Psy Shell v0.10.4 (PHP 7.4.5 — cli) by Justin Hileman
>>> __DIR__
=> "/Users/gabriel.ostrolucky/Documents/enrola/project"
>>> require 'vendor/autoload.php';
=> Composer\Autoload\ClassLoader {#11}
>>> $uri = new \GuzzleHttp\Psr7\Uri('action=add');
PHP Fatal error:  Class 'GuzzleHttp/Psr7/Uri' not found in Psy Shell code on line 1
>>>
```

**Comment by kapitanluffy** [comment] 2020-06-02 12:02
does your directory have a composer.json or lock file? It actually should automatically include the autoloader file

**Comment by ostrolucky** [comment] 2020-06-02 15:17
```
❯ ls /Users/gabriel.ostrolucky/Documents/enrola/project | grep composer
composer.json
composer.lock
```

**Comment by bobthecow** [comment] 2020-06-02 17:27
Are you using locally or globally installed psysh? Is it the pre-bundled phar or composer-based? Can you paste the output of `psy\info()`?

**Comment by ostrolucky** [comment] 2020-06-02 18:23
globally

```
[
     "PsySH version" => "v0.10.4",
     "PHP version" => "7.4.5",
     "OS" => "Darwin",
     "default includes" => [],
     "require semicolons" => false,
     "error logging level" => 32767,
     "config file" => [
       "default config file" => null,
       "local config file" => null,
       "PSYSH_CONFIG env" => false,
     ],
     "loop listeners" => [
       "Psy\ExecutionLoop\ProcessForker",
     ],
     "commands" => [
       "help" => "Psy\Command\HelpCommand",
       "?" => "Psy\Command\HelpCommand",
       "ls" => "Psy\Command\ListCommand",
       "dir" => "Psy\Command\ListCommand",
       "dump" => "Psy\Command\DumpCommand",
       "doc" => "Psy\Command\DocCommand",
       "rtfm" => "Psy\Command\DocCommand",
       "man" => "Psy\Command\DocCommand",
       "show" => "Psy\Command\ShowCommand",
       "wtf" => "Psy\Command\WtfCommand",
       "last-exception" => "Psy\Command\WtfCommand",
       "wtf?" => "Psy\Command\WtfCommand",
       "whereami" => "Psy\Command\WhereamiCommand",
       "throw-up" => "Psy\Command\ThrowUpCommand",
       "timeit" => "Psy\Command\TimeitCommand",
       "trace" => "Psy\Command\TraceCommand",
       "buffer" => "Psy\Command\BufferCommand",
       "buf" => "Psy\Command\BufferCommand",
       "clear" => "Psy\Command\ClearCommand",
       "edit" => "Psy\Command\EditCommand",
       "sudo" => "Psy\Command\SudoCommand",
       "history" => "Psy\Command\HistoryCommand",
       "hist" => "Psy\Command\HistoryCommand",
       "exit" => "Psy\Command\ExitCommand",
       "quit" => "Psy\Command\ExitCommand",
       "q" => "Psy\Command\ExitCommand",
     ],
     "updates" => [
       "update available" => false,
       "latest release version" => "v0.10.4",
       "update check interval" => "weekly",
       "update cache file" => "~/.config/psysh/update_check.json",
     ],
     "pcntl" => [
       "pcntl available" => true,
       "posix available" => true,
       "use pcntl" => true,
     ],
     "input" => [
       "interactive mode" => "auto",
       "input interactive" => true,
     ],
     "readline" => [
       "readline available" => true,
       "readline enabled" => true,
       "readline service" => "Psy\Readline\Libedit",
       "readline library" => "EditLine wrapper",
       "readline name" => "psysh",
     ],
     "output" => [
       "color mode" => "auto",
       "output decorated" => null,
       "output verbosity" => "normal",
     ],
     "history" => [
       "history file" => "~/.config/psysh/psysh_history",
       "history size" => null,
       "erase duplicates" => null,
     ],
     "docs" => [
       "manual db file" => null,
       "sqlite available" => true,
     ],
     "autocomplete" => [
       "tab completion enabled" => true,
       "bracketed paste" => false,
       "custom matchers" => [],
     ],
   ]
```

**Comment by bobthecow** [comment] 2020-06-02 19:18
That's really strange. I can't reproduce it with a global composer install, but it's doing the same thing for me with a global phar install.

The weirdest part is if you run `require 'test.php'` inside psysh it'll work (at least it does for me). I'll dig into this a bit more.

**Comment by bobthecow** [comment] 2020-06-02 19:22
Calling `require 'vendor/autoload.php'` is getting the phar's autoload, not the one in the current directory:

<img width="762" alt="Screen Shot 2020-06-02 at 12 21 53 PM" src="https://user-images.githubusercontent.com/53660/83560851-b6c68000-a4cb-11ea-92e5-f64e2cf5be64.png">

**Comment by ostrolucky** [comment] 2020-06-02 20:05
Indeed. Well, that's confusing. I would suggest to make phar load current dir's composer autoloader automatically though, like https://github.com/bobthecow/psysh/issues/640#issuecomment-637495742 suggests should already happen.

**Comment by bobthecow** [comment] 2020-06-02 20:38
If you install PsySH as a local dependency it'll defer to the current directory's composer autoloader.

Ideally we can make it so nothing ever unintentionally includes something from the phar. Worst case, I suppose we could change the vendor path to something ridiculous to keep it from colliding.

**Comment by ostrolucky** [comment] 2020-06-02 20:52
> If you install PsySH as a local dependency it'll defer to the current directory's composer autoloader.

I know, but I personally don't see including psysh as project dependency acceptable - it's not a library and neither something CI setup runs. And it's a tool that should work for every project, I can't be expected to start including psysh for all 100 projects that I have cloned in my local machine.

> Ideally we can make it so nothing ever unintentionally includes something from the phar. Worst case, I suppose we could change the vendor path to something ridiculous to keep it from colliding.

Indeed that would technically be a solution for this issue. I would personally welcome if psysh automatically've done autoloader inclusion for current workdir though, that way I would never run into this issue in the first place, because I wouldn't have to attempt including this autoloader manually. But perhaps this is for another issue.

**Comment by bobthecow** [comment] 2020-08-13 16:12
Oh boy. I _think_ I know what's going on here.

So PHP intercepts filesystem functions when called from inside a Phar, and resolves them to files with those names in the Phar, when they exist. This is normally what you want. That way when an Phar file tries to `require 'vendor/autoload.php'` it gets _the Phar's_ autoloader, not yours.

Unfortunately, it also seems to cache the result. Or maybe it only affects us because technically the code we're running in PsySH is being `eval`'d _inside_ the Phar? Not quite sure. Regardless, depending on where `require` is first called, it'll resolve to either the Phar's version or the filesystem version, and future calls will use that version even if they weren't called from inside the Phar.

To make it even more fun, even if you explicitly check what it'll be resolved to with `stream_resolve_include_path`, PHP omits the bit about it actually resolving to the `phar://` path when you try to run it :grimacing:

I've got a hacky fix: implicitly convert `require 'vendor/autoload.php'` to `require './vendor/autoload.php'` for any filename that collides with something in the Phar. Filesystem calls to relative (or absolute) paths don't get hijacked by Phar, so the fix prevents this instance of the bug. But I don't love it. It depends on us correctly resolving to the right relative include. From my limited testing it works, but I'm sure there are weird `include_path` values out there that would break this.

The other approach that might work is to "namespace" all files inside the Phar—similar to the way we namespace code—so inside the Phar everything is rewritten to reference `$hash/vendor/autoload.php`, etc. It'd have to be an extension to Box, and would have to do a bunch of static analysis similar to the code namespacing stuff, so I'm not sure how feasible this is. What do you think @theofidry?

**Closed** 2020-12-04 01:12 UTC
