### ISSUE TITLE
Call to a member function fetchColumn() on boolean

### ISSUE THREAD

**Issue by tgr** [bobthecow/psysh#741] opened 2022-08-21 04:21 UTC
I get this error whenever I try to use the `doc` command:
```
Psy Shell v0.11.8 (PHP 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b+wmf1 — cli) by Justin Hileman
>>> doc anyMethod
PHP Error:  Call to a member function fetchColumn() on boolean in /some/path/vendor/psy/psysh/src/Command/DocCommand.php on line 247
```
(The query that fails is `SELECT doc FROM php_manual WHERE id = %s`.)

I'm sure my local installation is messed up in some way, but a more informative error message would be nice.

**Comment by tgr** [comment] 2022-08-21 04:37
I think this is simply because the format of the file changed over time, and my SQLite file was very old? Re-downloading it fixed the issue.

Also, I got the error whether I used `doc` for a standard PHP method or one in the codebase, even though the latter is supposed to work without downloading the manual, so maybe the order of checks could be improved there.

**Comment by bobthecow** [comment] 2022-08-22 13:16
This is strange. I spot checked several revisions of the manual, including the first version ever, and I can't reproduce this issue. All of them display docs from the manual and local code just fine.

You wouldn't happen to still have the manual db that was erroring, would you?

**Comment by bobthecow** [comment] 2022-08-22 17:59
I just pushed a change to keep issues with the manual DB from breaking the `doc` command. It won't fix the underlying reason your manual db didn't work, but unless I can repro the issue I'm not sure what else I can do there :-/

**Closed** 2022-08-22 17:58 UTC

**Comment by tgr** [comment] 2022-08-23 03:43
Turns out it wasn't a valid SQLite file at all, I suppose the php.net URL structure changed and my update script was fetching some HTML error page. Sorry, should have checked first :(
Still, I think this is a nice improvement, thanks! 99% of the time I want the doc for userspace functions so if that's more robust, that's a plus.

**Comment by bobthecow** [comment] 2022-08-23 04:01
Great, thanks for checking.
