### ISSUE TITLE
When using eval(\Psy\sh()); the startupMessage appears again

### ISSUE THREAD

**Issue by prebenlm** [bobthecow/psysh#573] opened 2019-10-02 11:21 UTC
I've configured a startupMessage for some projects. When using eval(\Psy\sh()); the startupMessage appears again. Is it something I can avoid or is it a bug or working as intended? :)

**Comment by bobthecow** [comment] 2019-10-03 03:10
Do you mean if you start a PsySH session while you're already in the middle of a PsySH session? If so, then yes, you should see a startup message again. Because it's a new session!

**Comment by prebenlm** [comment] 2019-10-03 05:54
I guess you're technically correct, it's just that to me it feels like the same session. Since I'm not the one manually starting the session, it's Psysh itself starting it. 

1. I start Psysh
2. I call on a class and method that contains eval(\Psy\sh()); for example: MyClass::debugMe();
3. Psysh initializes a new shell automatically from the shell

Either way, I ended up figuring out a solution for me. 
	if (!isset($_SERVER['Psy_startupMessage_sent'])) {
		$_SERVER['Psy_startupMessage_sent'] = true;
		return array_merge($myDefaultConfig, [
			'startupMessage' => $message
		]);
	}

**Comment by bobthecow** [comment] 2019-11-23 20:58
Thinking about it a bit, I think it would be _less_ clear to not have that second message. Because if you're in a session started from inside a session, you'll have to `exit` twice before you're back out. Just silently entering a nested shell would be super confusing.

Closing as "working as designed" :)

**Closed by bobthecow** 2019-11-23 20:58 UTC
